name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - .github/workflows/*

jobs:
  publish:
    runs-on: ubuntu-latestname: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore: 
      - .github/workflows/*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.Js
        uses: actions/setup-node@v2
        with:
          node-version: '17.3.0'
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}} 
      - name: Install dependencies
        run: |
          npm install
          zip -r Flow.Launcher.Plugin.ChatGPTJS.zip . -x '*.git*'
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: 'Flow.Launcher.Plugin.ChatGPTJS.zip'
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: List files in root directory
        run: ls -la
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.2'
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: plugin.json
          property: Version
      - name: Install dependencies
        run: |
          npm install
          zip -r flow.Launcher.Plugin.ChatGPTJS.zip . -x .git\* -x .github\* -x .vscode\* -x .idea\* -x .gitignore -x .gitattributes -x .editorconfig -x .prettierrc -x .eslintrc.json
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: flow.Launcher.Plugin.ChatGPTJS.zip
          tag_name: ${{ steps.version.outputs.value }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
